version: "3"
services:
  postgrest2sqlserver:
    image: ghcr.io/ninanor/postgrest2sqlserver:main
    build: .
    command: "cat exported.tsv"
    #command:  /opt/mssql-tools/bin/bcp dbo.Table in exported.tsv -S servername -d databasename -U username -P password -c -F 2
    environment:
      - URL
      - PK_NAME
      - CONSUMER_TOKEN
      - CONTENTPROFILE
      - DELETE
